[package]
name = "tokenizers-python"
version = "0.13.3"
authors = ["Anthony MOI <m.anthony.moi@gmail.com>"]
edition = "2021"

[lib]
name = "tokenizers"
crate-type = ["cdylib"]

[dependencies]
rayon = "1.7"
serde = { version = "1.0", features = [ "rc", "derive" ]}
serde_json = "1.0"
libc = "0.2"
env_logger = "0.10"
pyo3 = "0.19"
numpy = "0.19"
ndarray = "0.13"
onig = { version = "6.4", default-features = false }
itertools = "0.10"

[dependencies.tokenizers]
version = "*"
path = "../../tokenizers"

[dev-dependencies]
tempfile = "3.1"
pyo3 = { version = "0.19", features = ["auto-initialize"] }

[features]
default = ["pyo3/extension-module"]

[profile.release]
lto = "fat"
